name: "Twingate"
description: "Add-on to add Twingate agent into Home Assistant for private VPN tunnel"
version: "1.0.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386